### ISSUE TITLE
Default invocation broken for 32bit targets

### ISSUE THREAD

**Issue by BigJim** [avast-tl/retdec-idaplugin#64] opened 2020-08-26 03:16 UTC
The default plugin invocation (run = 0) works fine for 64bit windows executable targets, but 32bit plugin invokes the (run = 1) function always. Asks for a file to decompile and if I give it a reference file to decompile it keeps asking for a file again if I click on any address in the decompile window.

This is using IDA for Windows 7.5.200728

**Comment by PeterMatula** [comment] 2020-08-27 10:58
This is strange:
* I'm unable to reproduce it on my system with IDA 7.5.200728.
* Both 32 and 64 bit versions are built and packaged at once, from the same source code. So I don't know what could have happened.

Can you make sure, there is no old RetDec-related configuration in `plugins/plugins.cfg`? Although, it should be applied to both `ida` and `ida64`. But anyway, if there is, remove everything and try it again.

**Comment by erazor-de** [comment] 2020-11-01 20:01
I can confirm this different behaviour for ida and ida64 7.5.201028 on Linux. I compiled retdec-idaplugin from source and have nothing related in plugins/plugins.cfg.

**Comment by erazor-de** [comment] 2020-11-02 18:34
My problem arises when getInputPath() can't find the source that was used creating the IDA database. It seems it searches the original path stored in the database and the actual path. In my case I tried a database created by a gdb remote debugging session with ida and a regular executable on disk with ida64. Hence my confusion.
Does retdec need the source file? Can't it take the binary data out of the database?

**Comment by PeterMatula** [comment] 2023-05-05 11:02
Yes, RetDec IDA plugin, as it is implemented now, does need to have access to the original binary file that is being analyzed. It would be ideal if it could simply take bytes from IDA and decompile those, but it cannot.

I'm closing this, as this is probably the cause of problem, and it would require a decent amount of changes in RetDec itself to accept bytes instead of files.

**Closed as completed by PeterMatula** 2023-05-05 11:02 UTC
