### ISSUE TITLE
Decompilation is not properly configured. 

### ISSUE THREAD

**Issue by b1ngoo** [avast-tl/retdec-idaplugin#32] opened 2018-07-20 02:45 UTC
I configured it according to the instructions of user_guide:
```
1. Install Python 3 and Pygments.
2. Download the Windows installation package (Table 2) from the project’s release
page.
3. Copy retdec.dll to the IDA’s plugin directory (<IDA_ROOT>/plugins).
```
This is my Python3 environment:
```
C:\Users\*****\AppData\Local\Programs\Python\Python35>python -m pip list
pip (8.1.1)
Pygments (2.2.0)
setuptools (20.10.1)
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command
```
![image](https://user-images.githubusercontent.com/32893618/42980529-5916c5cc-8c0a-11e8-92db-8111213797f7.png)
Then,  I copy retdec.dll to the IDA’s plugin directory:
![image](https://user-images.githubusercontent.com/32893618/42980428-cb6e0938-8c09-11e8-931b-3f4772ae8e29.png)
But when using it, this problem has arisen:
![image](https://user-images.githubusercontent.com/32893618/42980443-e4bd04f2-8c09-11e8-9124-be872f09023a.png)

Hmm, So what is going on here? Thanks

**Comment by PeterMatula** [comment] 2018-07-27 08:27
Did you also install RetDec itself? Can you run `bash retdec-decompiler.sh --help` from you command line? See section _2.2 RetDec_ in `user_guide.pdf` the latest release.

**Comment by PeterMatula** [comment] 2018-08-22 08:25
Can you try it now with a new release? We got rid of Bash.

**Comment by NiceneNerd** [comment] 2018-08-31 23:55
I'm getting this error on the new version (RetDec 3.2 and the latest plugin) using `retdec-decompiler.py`. It's in my PATH and runs fine from command line.

**Comment by JorgeTebruski** [comment] 2018-09-01 05:32
Same problem reproduced.

**Comment by NiceneNerd** [comment] 2018-09-01 11:31
Possibly relevant: IDAPython uses 2.7, but when I try to run RetDec outside of IDA it only works with Python 3. If I try to test `retdec-decompiler.py` using the `execfile` in the IDA Python console, it gives me a syntax error that is definitely due to changes between 2.7 and 3.

```
Python>execfile("C:\\users\\macad\\Downloads\\utilities\\retdec\\bin\\retdec-decompiler.py")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\users\macad\Downloads\utilities\retdec\bin\retdec-decompiler.py", line 14, in <module>
    retdec_signature_from_library_creator = importlib.import_module('retdec-signature-from-library-creator')
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Program Files\IDA 7.0\python\retdec-signature-from-library-creator.py", line 14, in <module>
    utils = importlib.import_module('retdec-utils')
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Program Files\IDA 7.0\python\retdec-utils.py", line 292
    print('Error: %s' % error, file=sys.stderr)
```

**Comment by ftk-sostupid** [comment] 2018-09-02 13:55
I got the same problem. I got an "syntax error" in retdec-utils.py when I run the retdec-decompiler.py with windows cmd.
So I can't config the plugin correctly.
But when I run it in pycharm, it's ok.
By the way, the error code is Line 292 of retdec-utils.py.
`print('Error: %s' % error, file=sys.stderr)`

**Comment by NiceneNerd** [comment] 2018-09-03 01:30
@ftk-sostupid I got that error when using Python 2.7 but not Python 3.

**Comment by ftk-sostupid** [comment] 2018-09-03 02:30
@NiceneNerd I got that in both python2.7 and python3.6...

**Comment by PeterMatula** [comment] 2018-09-03 06:42
@ftk-sostupid What does the error say? I don't use pycharm, so can you elaborate on what does _"But when I run it in pycharm, it's ok."_ mean? Does `retdec-decompiler.py` work when you somehow run it from pycharm, but does not when you execute it from cmd? As @NiceneNerd said, this looks like you are running it in Python 2.7.

**Comment by PeterMatula** [comment] 2018-09-03 06:44
@NiceneNerd Does it work when you don't rely on `PATH` and configure the path to the `retdec-decompiler.py` script in the configuration dialog?

**Comment by ftk-sostupid** [comment] 2018-09-03 06:50
@PeterMatula The error is **"Syntax Error"**. It mentioned the error happens in **retdec-utils.py, Line 292**
That line is `print('Error: %s' % error, file=sys.stderr)`. So I am very confused. 
And I tried in both 2.7 and 3.6. I got error when I use **Windows cmd** or **Powershell**
I got all things OK in Pycharm. I can run every script smoothly in Pycharm.

**Comment by PeterMatula** [comment] 2018-09-03 11:14
@ftk-sostupid That error really looks like you are running it in Python 2. So, can you try the following?

Edit `retdec-decompiler.py` in the RetDec `bin` directory. Add these lines at the start, so it looks like this:
```py
#!/usr/bin/env python3

"""Decompiles the given file into the selected target high-level language."""

### add these lines
from __future__ import print_function
import sys;
print(sys.version_info)
sys.exit(0)

### the rest of the original content ...
```

Then run it in 3.6 as you said you did. Output should look like this:
```
sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```
If it does look like that and it is still throwing that error, then something really fishy is going on.

**Comment by NiceneNerd** [comment] 2018-09-03 13:37
@PeterMatula No, whether I specify the script path or rely on PATH, it gives me a blank error and then says it's not properly configured.

**Comment by PeterMatula** [comment] 2018-09-03 13:39
@NiceneNerd Is the blank error an empty warning like this?
![blank-warning](https://user-images.githubusercontent.com/20342097/44989838-756c0e00-af8f-11e8-8504-39c5aa771a27.png)

**Comment by NiceneNerd** [comment] 2018-09-03 13:40
@PeterMatula That's just it.

**Comment by PeterMatula** [comment] 2018-09-03 13:47
Ok, tomorrow I will try to publish a new release. Hopefully it will fix most/all problems here. See https://github.com/avast-tl/retdec-idaplugin/issues/29#issuecomment-417363723 for more details + I fixed the empty warning window in `master`.

The empty window was caused by a typo in a warning dialog related to python command execution. It is possible RetDec plugin is unable to execute Python from your IDA. In the current `master`, it is possible to explicitly configure path to Python binary to use, so it should be working as long as you use the same Python that is run in `cmd.exe`.

**Comment by ftk-sostupid** [comment] 2018-09-03 13:54
@PeterMatula I added your code and run. I got result like:
![wv _r8 msww i6pp 6bn](https://user-images.githubusercontent.com/30171892/44990540-e3cac380-afc3-11e8-8ab0-e28615b6f13c.png)
And retdec-decompiler.py is:
![h6nxvxvibr8rk gim rc](https://user-images.githubusercontent.com/30171892/44990355-58513280-afc3-11e8-8855-e0cee4a46e90.png)
And I still got the same blank error and an empty warning like you just mentioned above after I added those code.

**Comment by PeterMatula** [comment] 2018-09-03 14:13
@ftk-sostupid Well, clearly Python 3.6.5 was not used to execute `retdec-decompiler.py` - Python 2.7.15 was used instead. So you did not try it with Python 3.6 as you wrote above - you only run `python` by itself which gave you 3.6.5.

I have no idea why your system behaves like this (`python` command runs 3.6.5, but script execution runs `2.7.15`), but you need to make sure 3.6.5 is used for `retdec-decompiler.py`. Note that [shebangs](https://en.wikipedia.org/wiki/Shebang_(Unix)) do not work on Windows, so the line `#!/usr/bin/env python3` will not do this for you. You have several possibilities:
* Run it explicitly like `python3 retdec-decompiler.py` (if `python3` command exists), `python3.6 retdec-decompiler.py` (if `python3.6` command exists), or maybe even `python retdec-decompiler.py` (since it looks like `python` itself gives you 3.6.5).
* Use standard way to execute Python 3 on Windows `py -3 retdec-decompiler.py` (if `py` command exists).
* Make sure scripts are executed with Python 3. I don't know Windows enough to tell you exactly what to do, but if I had to guess I would say there is something wrong with your `PATH` (Is Python 3 before Python 2? If it is not, it is very strange that `python` gives you 3.6.5 though).

One of these should work and run `retdec-decompiler.py` from command line. The release I was talking about will make it possible to chose in config dialog the Python interpreter to use, so it should take care of things when run from IDA.

**Comment by ftk-sostupid** [comment] 2018-09-03 14:16
@PeterMatula Thanks a lot for your help. It's very nice of you. 👍

**Comment by NiceneNerd** [comment] 2018-09-03 14:23
@ftk-sostupid The problem in your case is that Windows doesn't use PATH to determine how to directly execute Python scripts. It uses the general file association system, so in this case the Python 2.7 executable is probably the default handler for `.py` files. The fix is to use Open With to change the default `.py` handler to the Python 3 executable.

**Comment by ftk-sostupid** [comment] 2018-09-03 14:26
@NiceneNerd I agreed. I got another problem that my python in IDA is py2...just like:
![0i5 b50 k2awg2 y_kxai0](https://user-images.githubusercontent.com/30171892/44991956-66ee1880-afc8-11e8-8498-2050d6b83d9d.png)
 
I'm trying to solve this.

**Comment by PeterMatula** [comment] 2018-09-03 14:30
IDA comes with built-in Python 2.7, so you don't need to (and you probably can't) change that. RetDec plugin is not using IDA's Python, but a system Python, so all you need to do is configure your system in a way to prefer Python 3. Or you can wait for tomorrow for a new release that will make it possible to chose path to Python interpreter to use.

**Comment by ftk-sostupid** [comment] 2018-09-03 14:32
@PeterMatula @NiceneNerd I figure it out totally. Thanks for your both. I have learnt a lot.

**Comment by PeterMatula** [comment] 2018-09-04 15:01
Well, the new release will be tomorrow - today I ended up refactoring the user guide generation, plugin version distribution, and automated release package generation - all using pure CMake - and there was no time left to put it to use and generate the release itself.

**Comment by PeterMatula** [comment] 2018-09-05 09:38
RetDec IDA plugin version 0.7 is out. It will let you configure the path to Python 3 interpreter. I hope it will solve all the problems here.

Please let me know if it helped, so that I can either close this or fix new problems - if there are any.

**Comment by NiceneNerd** [comment] 2018-09-05 10:51
Looks like it works for me now. Many thanks!

**Comment by JorgeTebruski** [comment] 2018-09-05 14:29
Now it's working for me, thanks PeterMatula.

**Closed as completed** 2018-09-06 07:43 UTC
Labels: O-windows, P-run, Q-discussion

**Comment by ghost** [comment] 2019-10-26 23:41
The bug is now back, with IDA Pro 7.2 and all supported versions of Python.

**Comment by s3rvac** [comment] 2019-12-22 05:42
@kazblox Please, open a [new ticket](https://github.com/avast/retdec-idaplugin/issues/new) if the issue still persists for you.
