### ISSUE TITLE
Decompilation fails with "Unfinished decompilation was KILLED !!!"

### ISSUE THREAD

**Issue by op0x59** [avast-tl/retdec-idaplugin#34] opened 2018-10-05 05:02 UTC
```
[RetDec info]   :	Running the decompilation command ...
[RetDec info]   :	Working on input file "C:\Users\morph\Desktop\Sandbox\MalwareTest.exe".
[RetDec info]   :	Found retdec-decompiler.py at C:\Users\morph\Desktop\Database\Reverse-Engineering\Decompilers\retdec\bin\retdec-decompiler.py -> plugin is properly configured.
[RetDec info]   :	Running retargetable decompiler plugin:
[RetDec info]   :	Unfinished decompilation was KILLED !!!
[RetDec info]   :	Saving IDA database ...
Flushing buffers, please wait...ok
[RetDec info]   :	IDA database saved into :  C:\Users\morph\Desktop\Sandbox\MalwareTest.dec-backup.idb
[RetDec info]   :	Generating retargetable decompilation DB ...
[RetDec info]   :	Decompile input ...
[RetDec info]   :	Local decompilation ...
[RetDec info]   :	Decompilation command: "C:\Users\morph\Desktop\Database\Reverse-Engineering\Decompilers\retdec\bin\retdec-decompiler.py"
"C:\Users\morph\Desktop\Sandbox\MalwareTest.exe"
--config="C:\Users\morph\Desktop\Sandbox\MalwareTest.idb.json"
--color-for-ida
-o
"C:\Users\morph\Desktop\Sandbox\MalwareTest.exe.c"
--select-decode-only
--select-ranges="0xa50e70-0xa51092"
[RetDec info]   :	Running the decompilation command ...
```

Pictures of Settings:
[Settings Picture](https://vgy.me/AweNyJ.png)

**Comment by s3rvac** [comment] 2018-10-05 05:06
Hi. A couple of questions:
* What IDA version do you use?
* What version of the RetDec IDA plugin do you use?
* What version of RetDec do you use?
* Does it fail for all files that you try to decompile or only for the reported one? If only for the reported one, could you please attach it so we can try to reproduce the issue?

**Comment by op0x59** [comment] 2018-10-05 05:11
> Hi. A couple of questions:
> 
> * What IDA version do you use?
> * What version of the RetDec IDA plugin do you use?
> * What version of RetDec do you use?
> * Does it fail for all files that you try to decompile or only for the reported one? If only for the reported one, could you please attach it so we can try to reproduce the issue.

- IDA Version: 7.0
- v0.7
- v3.2
- Different error for another test, [Test 2](https://vgy.me/sA4YeO.png)
  No longer produces the "Unfinished decompilation was KILLED !!!" log

Edit: I have fixed my problem, I was missing a file from the original retdec files.

**Comment by s3rvac** [comment] 2018-10-05 05:14
Could you please attach the input binaries that you are trying to decompile? You can zip them and upload them here via _Attach files_ in the comment box.

**Comment by s3rvac** [comment] 2018-10-05 05:23
> Edit: I have fixed my problem, I was missing a file from the original retdec files.

Has this fixed both of the problems that you have reported or just the one?

**Comment by s3rvac** [comment] 2018-10-05 06:44
Just a guess concerning the originally reported issue: Did you run multiple decompilations at the same time?

**Comment by op0x59** [comment] 2018-10-05 08:53
> Just a guess concerning the originally reported issue: Did you run multiple decompilations at the same time?

This has fixed both problems, and yes I did run multiple decompilations at the same time.

**Comment by s3rvac** [comment] 2018-10-05 08:58
Unfortunately, the plugin currently does not support multiple simultaneous decompilations. Once you run a second decompilation, the first one gets automatically killed.

I am marking this as closed since the issue was resolved for you.

**Closed as completed by s3rvac** 2018-10-05 08:58 UTC
Labels: P-run

**Comment by PeterMatula** [comment] 2018-10-05 12:42
I created an issue to support multiple decompilations - #35. This is however not a priority right now, since it would be quite difficult to implement and we have some serious problems even with a single decompilation.
