### ISSUE TITLE
retdec not loading

### ISSUE THREAD

**Issue by Jirubizu** [avast-tl/retdec-idaplugin#61] opened 2020-05-10 17:20 UTC
I am unsure what you would like me to provide in terms of logs. However, the plugin loaded one time and after a restart it did not load at all. It doesnt recognise any of the keybindings nor do I find any reference of the plugin anywhere in IDA.

Not sure for the cause

**Comment by PeterMatula** [comment] 2020-05-18 07:26
1. Did it work the first time?
2. Is the plugin still in the IDA plugin directory?
3. Did you update IDA or something like that?

**Comment by PeterMatula** [comment] 2021-01-22 10:43
No reaction -> closing.
Moreover, the issue is probably no longer valid since the release of [v1.0](https://github.com/avast/retdec-idaplugin/releases/tag/v1.0).

**Closed as completed by PeterMatula** 2021-01-22 10:43 UTC
Labels: S-invalid
