### ISSUE TITLE
Unable to parse decompilation output: The document is empty.

### ISSUE THREAD

**Issue by flyingbird** [avast-tl/retdec-idaplugin#70] opened 2022-09-07 11:32 UTC
When I use Ctrl+D, It says Unable to parse decompilation output: The document is empty.
<img width="577" alt="iShot_2022-09-07_19 29 31" src="https://user-images.githubusercontent.com/1467920/188868361-8f5afd45-8e55-42f7-a280-715d3dfa5663.png">

**Comment by flyingbird** [comment] 2022-09-07 13:55
I can see:[RetDec info]   :	RetDec version 1.0-ida80 loaded OK
I pressed Ctrl+D after "The initial autoanalysis has been finished."
but it still says "Unable to parse decompilation output: The document is empty."

**Comment by flyingbird** [comment] 2022-09-09 01:33
I think it lacks of some files for working on mac.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1467920/189253590-849353a0-3f16-4f3c-9103-b068fdcbe8c9.png">

**Comment by PeterMatula** [comment] 2022-09-12 06:51
Sorry, I don't own a mac machine and don't have an IDA license for it either. So, I have never tried the plugin on mac and I don't know if it works.

Going just by the message, it is from RetDec IDA plugin, not the RetDec itself, and the `The document is empty` is a RapidJSON's parsing error message. It looks like the decompilation either failed entirely or passed but generated an empty result.  
* Does this happen for all functions, or just in some cases? Are you able to decompile anything?
* Did you build the plugin yourself?
* Would you try to build RetDec itself and try if it works for you without getting the IDA plugin into it?

**Comment by flyingbird** [comment] 2022-09-12 08:05
> Sorry, I don't own a mac machine and don't have an IDA license for it either. So, I have never tried the plugin on mac and I don't know if it works.
> 
> Going just by the message, it is from RetDec IDA plugin, not the RetDec itself, and the `The document is empty` is a RapidJSON's parsing error message. It looks like the decompilation either failed entirely or passed but generated an empty result.
> 
> * Does this happen for all functions, or just in some cases? Are you able to decompile anything?
> * Did you build the plugin yourself?
> * Would you try to build RetDec itself and try if it works for you without getting the IDA plugin into it?

1. Can not decompile anything.
2. Build by myself.
3. I'll try it later.

**Comment by flyingbird** [comment] 2022-09-12 08:20
> Sorry, I don't own a mac machine and don't have an IDA license for it either. So, I have never tried the plugin on mac and I don't know if it works.
> 
> Going just by the message, it is from RetDec IDA plugin, not the RetDec itself, and the `The document is empty` is a RapidJSON's parsing error message. It looks like the decompilation either failed entirely or passed but generated an empty result.
> 
> * Does this happen for all functions, or just in some cases? Are you able to decompile anything?
> * Did you build the plugin yourself?
> * Would you try to build RetDec itself and try if it works for you without getting the IDA plugin into it?

I download retdec-v4.0-macos-64b.tar.xz
try run the command:
./retdec-decompiler.py ~/Desktop/test
report errors as below:
Error: failed to limit maximal memory to half of system RAM
Error: Decompilation to LLVM IR failed

**Comment by PeterMatula** [comment] 2023-05-09 09:47
Based on the error:
```
Error: failed to limit maximal memory to half of system RAM
Error: Decompilation to LLVM IR failed
```
It looks like the problem is with RetDec - a well known problem reported several times - when RetDec cannot handle some inputs due to time/memory complexity. Nothing that can be done on the RetDec IDA plugin side. A major improvement of RetDec itself would be needed. As such, I'm closing this.

**Closed as completed by PeterMatula** 2023-05-09 09:47 UTC
